language: node_js
node_js:
 - "node"

sudo: required
addons:
  chrome: stable

branches:
  only:
    - test

before_install:
 - npm install --save-dev jasmine
 - npm install --save-dev karma
 - npm install requirejs
 - npm install --save-dev karma-jasmine karma-chrome-launcher
 - npm install -g karma-cli

 script:
 - cd tests/ && karma start --single-run