sudo: required
language: node_js

node_js:
  - "stable"

sudo: required
addons:
  chrome: "stable"

before_install:
#  - export CHROME_BIN=chromium-browser
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start  # Setting up false screen for Chrome to work
  - npm install --save-dev jasmine
  - npm install --save-dev karma
  - npm install requirejs
  - npm install --save-dev karma-jasmine karma-chrome-launcher
  - npm install -g karma-cli

script:
  - cd tests/ && karma start --single-run
